### ISSUE TITLE
BUG: PMPro Add Member From Admin Add On – PHP Notice After Updating To v0.6

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-gift-aid#8]
**For moderators:** https://www.paidmembershipspro.com/forums/topic/bug-pmpro-add-member-from-admin-add-on-php-notice-after-updating-to-v0-6

The following PHP Notice is recorded in wp-debug log after updating Add Member From Admin Add On to v0.6 and adding a new member through the add-on.

Note: The member is added successful.

`[23-Nov-2019 17:13:41 UTC] PHP Notice: Undefined index: invoice_id in /home/customer/www/dev.ksa-uk.net/public_html/wp/wp-content/plugins/pmpro-gift-aid/pmpro-gift-aid.php on line 121`

Find a screenshot of the Add Member page and a relevant wp_debug.log extract attached.

PHP v7.1.33
WordPress v5.3
PMPro v2.1.4
Add Member From Admin Add On v0.6
Approvals Add On v1.3.4
Gift Aid Add On v1.2
Sponsored/Group Members Add On v0.6.3

[wp-debug.zip](https://github.com/strangerstudios/pmpro-gift-aid/files/3898701/wp-debug.zip)
![2019-11-23_17-25-55](https://user-images.githubusercontent.com/12136834/69758093-8259bc00-1156-11ea-91ad-e64005f7b5bb.png)

**Comment by kimcoleman** [comment]
Note: Paid Memberships Pro v3.0 and higher now includes a better pathway to create a new member and adjust their memberships. Navigate to Memberships > Members and click + Add Member.

We will continue to support this Add On for some time, but strongly recommend sites instead use this built-in method to create new members. We do not plan to adjust this for Gift Aid.
