### ISSUE TITLE
BUG: Gift Aid user meta not set to 0 if unchecked.

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-gift-aid#9]
There should be an else clause here to set `gift_aid` user meta to `0` to catch cases where the box was unchecked during checkout:
https://github.com/strangerstudios/pmpro-gift-aid/blob/a2b736ccb056404b67dab6d0af93f8a4251d9a91/pmpro-gift-aid.php#L36-L52

Meta key should probably also be `pmpro_` prefixed.

**Comment by MaximilianoRicoTabo** [comment]
Do we need to store the not checked value ? Isn't enough to assume that if it's not stored then wasn't checked ?

**Comment by kimcoleman** [comment]
@MaximilianoRicoTabo since this is stored in user meta, a user could complete checkout a first time and check box, then buy something else and uncheck it. The value for that user's order would still be "yes" (1).

**Comment by MaximilianoRicoTabo** [comment]
I just realized about this comment and prior PR. I think I fixed in yesterdays PR anyway @kimcoleman

**Comment by MaximilianoRicoTabo** [comment]
Yeap, here https://github.com/strangerstudios/pmpro-gift-aid/pull/16/files#diff-35f4ef2cc65ec483c2a5b6ccbab003ab18a7e5dff3f394c8b2a91f30abfe7f78R68 @kimcoleman
